recipes:
  global:
    # general development
    - dotfiles::bash_it
    - applications::git
    - dotfiles::gitconfig
    - dotfiles::projects

    # rails development stack
    - dotfiles::gem_setup
    - applications::rvm
    - applications::nodejs
    - applications::phantomjs
    - applications::heroku
    - applications::virtualbox
    - applications::vagrant

    # development tools
    - applications::sublime_text_3
    - applications::google-chrome
    - applications::firefox
    - applications::github_for_mac
    - applications::mou

attributes:
  rvm:
    default_ruby: "2.0.0-p451"
    rubies:
      2.0.0-p451: {}
  vagrant_plugins:
    - vagrant-berkshelf
    - vagrant-omnibus
  terminal:
    color_scheme: "Pro"
  bash_it:
    theme: tylenol
    enabled_plugins:
      completion:
        - defaults
        - bash-it
        - git
        - brew
        - gem
        - rake
        - ssh
      plugins:
        - git
        - ssh
        - ruby
        - rvm
        - vagrant
